#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Parse README.md into structured, machine-readable data.

The README of this repository is a large collection of Markdown tables
(one per category). This script converts it into:

  * data/apis.json  - full dataset with metadata (for programs)
  * data/apis.csv   - flat spreadsheet-friendly export
  * data/apis.js    - the same data as `window.APIS_DATA = [...]`,
                      loadable from index.html via file:// (no server needed)

Usage:
    python3 scripts/parse_apis.py                 # regenerate everything in data/
    python3 scripts/parse_apis.py --check         # parse only, print a summary
    python3 scripts/parse_apis.py --readme PATH --out-dir DIR

Only the Python standard library is used.
"""

import argparse
import csv
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_README = REPO_ROOT / 'README.md'
DEFAULT_OUT_DIR = REPO_ROOT / 'data'

CATEGORY_RE = re.compile(r'^###\s+(.+?)\s*$')
TITLE_LINK_RE = re.compile(r'^\[(.+?)\]\(\s*(https?://\S+?)\s*\)$')


def github_anchor(title: str) -> str:
    """Reproduce GitHub's heading-anchor slug (enough for this README)."""
    slug = []
    for ch in title.lower():
        if ch.isalnum():
            slug.append(ch)
        elif ch in (' ', '-'):
            slug.append('-')
    return ''.join(slug)


def parse_apis(readme_path=DEFAULT_README):
    """Return a list of API entries parsed from the README tables.

    Each entry is a dict with keys:
        name, url, description, auth (str or None), https (bool),
        cors ('yes' | 'no' | 'unknown'), category, category_anchor, line
    """
    apis = []
    category = None

    lines = Path(readme_path).read_text(encoding='utf-8').splitlines()
    for line_num, raw in enumerate(lines, 1):
        line = raw.strip()

        match = CATEGORY_RE.match(line)
        if match:
            category = match.group(1)
            continue

        # Tables before the first "### Category" heading (e.g. the sponsor
        # table at the top) are intentionally skipped.
        if category is None:
            continue
        if not line.startswith('|') or set(line) <= {'|', ':', '-', ' '}:
            continue

        segments = [seg.strip() for seg in line.split('|')[1:-1]]
        if len(segments) < 5:
            continue

        title_match = TITLE_LINK_RE.match(segments[0])
        if not title_match:
            continue

        auth = segments[2].strip('`').strip()
        cors = segments[4].strip().lower()
        apis.append({
            'name': title_match.group(1).strip(),
            'url': title_match.group(2),
            'description': segments[1],
            'auth': None if auth.lower() == 'no' or not auth else auth,
            'https': segments[3].strip().lower() == 'yes',
            'cors': cors if cors in ('yes', 'no') else 'unknown',
            'category': category,
            'category_anchor': github_anchor(category),
            'line': line_num,
        })

    return apis


def categories_of(apis):
    """Ordered unique category names."""
    seen = {}
    for api in apis:
        seen.setdefault(api['category'], None)
    return list(seen)


def write_json(apis, out_path: Path) -> None:
    payload = {
        'count': len(apis),
        'categories': categories_of(apis),
        'entries': apis,
    }
    out_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=1) + '\n',
        encoding='utf-8',
    )


def write_csv(apis, out_path: Path) -> None:
    fields = ['name', 'description', 'url', 'auth', 'https', 'cors', 'category']
    with out_path.open('w', encoding='utf-8', newline='') as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, extrasaction='ignore')
        writer.writeheader()
        for api in apis:
            row = dict(api)
            row['auth'] = row['auth'] or 'No'
            row['https'] = 'Yes' if row['https'] else 'No'
            writer.writerow(row)


def write_js(apis, out_path: Path) -> None:
    slim = [
        {k: api[k] for k in ('name', 'url', 'description', 'auth', 'https', 'cors', 'category')}
        for api in apis
    ]
    data = json.dumps(slim, ensure_ascii=False, separators=(',', ':'))
    out_path.write_text(
        '// Generated by scripts/parse_apis.py - do not edit by hand.\n'
        'window.APIS_DATA = ' + data + ';\n',
        encoding='utf-8',
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--readme', type=Path, default=DEFAULT_README,
                        help='path to README.md (default: repository root)')
    parser.add_argument('--out-dir', type=Path, default=DEFAULT_OUT_DIR,
                        help='output directory (default: data/)')
    parser.add_argument('--check', action='store_true',
                        help='parse and print a summary without writing files')
    args = parser.parse_args(argv)

    if not args.readme.is_file():
        print(f'error: README file not found: {args.readme}', file=sys.stderr)
        return 2
    apis = parse_apis(args.readme)
    if not apis:
        print(f'error: no API entries found in {args.readme}', file=sys.stderr)
        return 1

    categories = categories_of(apis)
    print(f'Parsed {len(apis)} APIs in {len(categories)} categories '
          f'from {args.readme}')

    if args.check:
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_json(apis, args.out_dir / 'apis.json')
    write_csv(apis, args.out_dir / 'apis.csv')
    write_js(apis, args.out_dir / 'apis.js')
    for name in ('apis.json', 'apis.csv', 'apis.js'):
        print(f'  wrote {args.out_dir / name}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
